# Generated by Django 3.2.9 on 2021-11-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.TextField()),
                ('Url_key', models.CharField(max_length=7)),
            ],
        ),
    ]
